name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401, E203, W503"
          max-line-length: "120"
          plugins: "flake8-bugbear==22.1.11 flake8-black"        
